### ISSUE TITLE
Add support for local file as m3u provider

### ISSUE THREAD

**Issue by Tibladar** [linuxmint/hypnotix#1]
Currently there's no way to add a local file as m3u provider, e.g. DVB-C devices can create those files.

Tried using
`gsettings set org.x.hypnotix providers "['Provider_Name:::file:///home/user/tv.m3u']"`
but it doesn't work:
```
No connection adapters were found for 'file:///home/user/tv.m3u'
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 50, in activate
    window = MainWindow(self)
  File "/usr/lib/hypnotix/hypnotix.py", line 152, in __init__
    self.reload()
  File "/usr/lib/hypnotix/hypnotix.py", line 283, in reload
    self.manager.load_channels(provider)
  File "/usr/lib/hypnotix/common.py", line 102, in load_channels
    with open(provider.path, "r") as file:
FileNotFoundError: [Errno 2] File or directory not found: '/home/user/.hypnotix/providers/providername'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] File or directory not found: '/var/crash/_usr_lib_hypnotix_hypnotix.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 50, in activate
    window = MainWindow(self)
  File "/usr/lib/hypnotix/hypnotix.py", line 152, in __init__
    self.reload()
  File "/usr/lib/hypnotix/hypnotix.py", line 283, in reload
    self.manager.load_channels(provider)
  File "/usr/lib/hypnotix/common.py", line 102, in load_channels
    with open(provider.path, "r") as file:
FileNotFoundError: [Errno 2] File or directory not found: '/home/user/.hypnotix/providers/providername'
```

Exchanging the `freeiptv` file with a custom one doesn't work as it gets overwritten.

**Comment by clefebvre** [comment]
Good point.
