### ISSUE TITLE
hypnotix freezes up

### ISSUE THREAD

**Issue by mandraid** [linuxmint/hypnotix#103]
I am running Ubuntu 20.04.2.  When I go to choose a station on hypnotix, the program seems to freeze up.  I see at the bottom of the screen, it says "IPTV: Loading channels".

**Comment by Axel-Erfurt** [comment]
does this happen at every station?

**Comment by mandraid** [comment]
yes

**Comment by LibertyDrew13** [comment]
It is also freezing for me. running kubuntu 20.04 all Python3 dependencies are installed.  Also, attempted to load my own playlist to see if perhaps it was just the server of the one that came with it./  The playlist loaded great and all of the channels were listed, However, like the original, it freezes whenever I attempt to play/open a channel stream. So not the playlist.  Is there a way to choose the video player? I feel like this could be the issue-but I have no idea. Thanks though to the people that made this. It looks great can't wait until I can get this up and running! Appreciate the efforts guys, like always...I will stop brown nosing now Im making myself sick.

**Comment by mwhickson** [comment]
I downloaded and installed the 1.1 DEB from GitHub and installed in Ubuntu 20.04.

(Linux box 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)

I noticed an error when navigating through to the player (for TV) and selecting a country (in my case, Canada).

The error appeared to have something to do with MPV and Wayland (I seem to recall something xid, and will post more detail if I can reproduce it).

Logging out, and using Ubuntu (no Wayland) results in things working fine, with stuttering on some channels (and the "not all channels work" caveat).

It seems a fresh Wayland session can produce the error condition, and subsequent runs fail silently.

It wasn't the error described here (https://stackoverflow.com/questions/45762522/get-gdk-window-from-xid-under-wayland), but does indicate I probably didn't hallucinate the xid part.

**Comment by mwhickson** [comment]
Found the logs...

(and should probably add that I did a minimal Ubuntu install (recently) in this case)

Aug 20 20:26:39 box hypnotix.desktop[16505]: Traceback (most recent call last):
Aug 20 20:26:39 box hypnotix.desktop[16505]:   File "/usr/lib/hypnotix/hypnotix.py", line 1018, in on_mpv_drawing_area_realize
Aug 20 20:26:39 box hypnotix.desktop[16505]:     self.reinit_mpv()
Aug 20 20:26:39 box hypnotix.desktop[16505]:   File "/usr/lib/hypnotix/hypnotix.py", line 1039, in reinit_mpv
Aug 20 20:26:39 box hypnotix.desktop[16505]:     input_vo_keyboard=True,osc=True, ytdl=True, wid=str(self.mpv_drawing_area.get_window().get_xid()))
Aug 20 20:26:39 box hypnotix.desktop[16505]: AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'

**Comment by Axel-Erfurt** [comment]
> AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'

try in terminal

```GDK_BACKEND=x11 hypnotix```

**Comment by mwhickson** [comment]
> try in terminal
> 
> `GDK_BACKEND=x11 hypnotix`

That resolved the "nothing happens"/error scenario; however, MPV jumps out of the Hypnotix window, and is larger than the area it would have consumed.

See the screenshot attached.

![hypnotix-wayland-x11](https://user-images.githubusercontent.com/86990649/130330839-8dcd8c32-286c-4e29-8108-cf26b356e5df.jpg)

**Comment by Axel-Erfurt** [comment]
add 

```vo=x11```

to mpv options in Settings.

**Comment by mwhickson** [comment]
Well, that worked!

Took me a bit to find the Settings... didn't realize it only stuck around on the main Hypnotix window (tried editing ~/.config/mpv/mpv.conf to set vo=x11... that didn't work)...

![Ubuntu_20 04-hypnotix-wayland-settings_options](https://user-images.githubusercontent.com/86990649/130716055-b866a7f1-bb5e-4639-8cb5-f50935923952.jpg)

![Ubuntu_20 04-hypnotix-wayland-vo-x11](https://user-images.githubusercontent.com/86990649/130716068-80a8e669-f165-4655-bdb2-a3f95ba66cfd.jpg)

![Ubuntu_20 04-hypnotix-wayland--fixed-view](https://user-images.githubusercontent.com/86990649/130716080-0fb410bb-90d9-4a5f-ab1e-7aab9777fbe9.jpg)
