### ISSUE TITLE
Please make an AppImage version

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/hypnotix#104]
This would be ideal for users of other distributions without dealing with all the intricacies of packaging. Thanks for considering!

**Comment by ivan-hc** [comment]
Hi, I'm working on an AppImage for Hypnotix using two scripts you can see on my repository at https://github.com/ivan-hc/Hypnotix-appimage : 
- [hypnotix-junest.sh](https://github.com/ivan-hc/Hypnotix-appimage/blob/main/hypnotix-junest.sh) creates an Archimage and it is at the base of my workflows, it creates an AppImage containing a portable Arch Linux container named JuNest (see [Archimage](https://github.com/ivan-hc/ArchImage)). Being a container, it shoul work on all distros with at least the kernel 2.6.x . You can already test one at https://github.com/ivan-hc/Hypnotix-appimage/releases/tag/continuous
- [hypnotix-deb.sh](https://github.com/ivan-hc/Hypnotix-appimage/blob/main/hypnotix-deb.sh) instead creates an AppImage the clasical way using [pkg2appimage](https://github.com/AppImageCommunity/pkg2appimage) and its based on Debian Stable+packages from Linux Mint. You can create it by yourself.

### I'm still investigating (see https://github.com/ivan-hc/Hypnotix-appimage/issues/2), and I also need help to made it work correctly!

Both of them have the same issue, i.e. after 1-2 times you change the channel, it crashes with the following message:
```
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
also
```
libEGL warning: DRI2: failed to authenticate
```

Here is a video of the one based on Debian, this is what happens when I run it:

https://private-user-images.githubusercontent.com/88724353/301916362-a58b2d52-570f-44c7-847b-09041c781b42.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTQzMDgsIm5iZiI6MTcwNjg5NDAwOCwicGF0aCI6Ii84ODcyNDM1My8zMDE5MTYzNjItYTU4YjJkNTItNTcwZi00NGM3LTg0N2ItMDkwNDFjNzgxYjQyLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE3MTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYWJlNDA4NmEzZjlmMDJhZTRkODhhMzQ1MTQ3OTk5MjkyOWNhNTc2ZDQ5NWFhMmY5ZmI5YmUwYmQyYjM3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sG40d_n1cxTONqpn7bqaiS6oCSf0tZ4ywoipu061y_Q

**Comment by faveoled** [comment]
My take using appimage-builder:
https://github.com/faveoled/hypnotix-appimage/blob/main/appimage-builder.yml

**Comment by ivan-hc** [comment]
@faveoled have you got a release ready to be tested?

**Comment by ivan-hc** [comment]
@faveoled just seen the the artifact from this workflow

https://github.com/faveoled/hypnotix-appimage/actions/runs/7388600331

Yu have a problem with `libmpv` similar to this https://github.com/ivan-hc/Hypnotix-appimage/issues/1 I had it too when creating the AppImage pbased on JuNest (Arch Linux container).

Recently I've built one using only .deb packages and started, but with the same issue of my first post here: after 2 channels, the AppImage crashes.

In your case, I think you need something in /usr/bin (maybe some glib-related binaries or `sdl2-config`... or something, I'm not sure. All I know is that the one based on JuNest was working after I included some files in /usr/bin with the keyword "ld" in the name.

You can check my deb-based appimage here:
- https://github.com/ivan-hc/Hypnotix-appimage/releases/tag/continuous

While the one based on JuNest is here:
- https://github.com/ivan-hc/Hypnotix-appimage/releases/tag/continuous-archimage

You can inspect them using the option `--appimage-extract` (the one based on JuNest has the binaries in /.junest/usr/bin).

I hope this will help you.

**Comment by ivan-hc** [comment]
@Altonss hi, I'm watching your repository. Is it working for you?

I'm always facing the same issue, after two times i change the channe, the app crashes with errors like this
```
CHANNEL: 'Rete 4 Ⓖ' (https://live02-seg.msf.cdn.mediaset.net/live/ch-r4/r4-clr.isml/index.m3u8)
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
CHANNEL: 'Canale 5 Ⓖ' (https://live02-seg.msf.cdn.mediaset.net/live/ch-c5/c5-clr.isml/index.m3u8)
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
libEGL warning: DRI2: failed to authenticate
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
```
have you faced the same issue? Have you solved it?

**Comment by ivan-hc** [comment]
@Altonss I'm not sure but this should be an issue related to my old Nvidia drivers (Debian Testing)
```
egl: failed to create dri2 screen
```
can you test this? https://github.com/ivan-hc/Hypnotix-appimage/releases/tag/continuous

**Comment by Sadi58** [comment]
@ivan-hc I tried your AppImage, and got the same error below as the Mint deb package installed on my Debian Testing system.
I have no idea as a user, but probably I would encounter the problem you mentioned if I could overcome this ;-)

```
System version of yt-dlp selected.
Traceback (most recent call last):
  File "/tmp/.mount_hypnotghkxMt/usr/lib/hypnotix/hypnotix.py", line 27, in <module>
    import mpv
  File "/tmp/.mount_hypnotghkxMt/usr/lib/hypnotix/mpv.py", line 53, in <module>
    backend = CDLL(sofile)
              ^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /lib/x86_64-linux-gnu/libmpv.so.2: undefined symbol: av_packet_side_data_get, version LIBAVCODEC_60
```

**Comment by ivan-hc** [comment]
@Sadi58 I know that my Hypnotix AppImages are buggy, this is why I'm here trying to find a solution, have cooperators and merge our ideas together to made it real.

> Note: I was happily using Hypnotix until a while ago when I installed Hypnotix 3.2 from MX Linux repositories on my Debian Testing system, which was Debian 12 (Bookworm).

For my personal use I switched to IPTVnator, at https://github.com/4gray/iptvnator and they have an official AppImage

> So, I guess it is probably working perfectly on Debian Stable now.

Nope, I don't think it would work into an AppImage based on Debian Stable, at current state.

Hypnotix is built to work with Linux Mint, around Linux Mint... like WebApp Manager, that instead is based on ICE from PeppermintOS, but ICE works everywhere, WebApp Manager not (I'm still talking about AppImages).

Also, I think that Hypnotix developers should care more about mantaining their product, at least on Linux Mint, and this repository is named https://github.com/linuxmint/hypnotix , user "linuxmint", so this is what the Linux Mint team care more about. Their OS.

@geckolinux at this point I think that this issue will follow the sort of many othyers abandoned and without support. Your distro is based on openSUSE, and developers have a long story of packaging distribution and their servers are rich of Appimages, as far I know.

That said, third party packaging is the way. I can see this issue as a meeting point, and I hope that this can bring as many developers and contributors as possible, not just costumers requesting alternative packages. As I said, I'm here searching cooperators or helping others improve their project with my ideas, if helpful.

Finally, I don't think Linux Mint developers would be interested in distribute their exclusive packages on other platforms. It's the harsh law of competition. If distros offered the same benefits, they wouldn't be so numerous.
