### ISSUE TITLE
hypnotis does not show channel list

### ISSUE THREAD

**Issue by joaopa00** [linuxmint/hypnotix#160]
kubuntu 21.04: X11 server

WHen clicking in a country, no channel is shown. But the gui is still responsive

piou@piou:~/Téléchargements$ hypnotix 
piou@piou:~/Téléchargements$ Loading providers...
Free-IPTV: Getting playlist...
Free-IPTV: Checking playlist...
Free-IPTV: Loading channels...
Could not load badge /usr/share/hypnotix/pictures/badges/germany.png
Could not load badge /usr/share/hypnotix/pictures/badges/germany.png
Could not load badge /usr/share/hypnotix/pictures/badges/germany.png
Could not load badge /usr/share/hypnotix/pictures/badges/germany.png
Could not load badge /usr/share/hypnotix/pictures/badges/germany.png
Could not load badge /usr/share/hypnotix/pictures/badges/austria.png
Could not load badge /usr/share/hypnotix/pictures/badges/switzerland.png
Could not load badge /usr/share/hypnotix/pictures/badges/liechtenstein.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Could not load badge /usr/share/hypnotix/pictures/badges/canada.png
Could not load badge /usr/share/hypnotix/pictures/badges/brazil.png
Could not load badge /usr/share/hypnotix/pictures/badges/brazil.png
Could not load badge /usr/share/hypnotix/pictures/badges/mexico.png
Could not load badge /usr/share/hypnotix/pictures/badges/mexico.png
Could not load badge /usr/share/hypnotix/pictures/badges/argentina.png
Could not load badge /usr/share/hypnotix/pictures/badges/australia.png
Could not load badge /usr/share/hypnotix/pictures/badges/newzealand.png
Could not load badge /usr/share/hypnotix/pictures/badges/japan.png
Could not load badge /usr/share/hypnotix/pictures/badges/india.png
Could not load badge /usr/share/hypnotix/pictures/badges/china.png
Could not load badge /usr/share/hypnotix/pictures/badges/taiwan.png
Could not load badge /usr/share/hypnotix/pictures/badges/singapore.png
Could not load badge /usr/share/hypnotix/pictures/badges/korea.png
Could not load badge /usr/share/hypnotix/pictures/badges/uk.png
Could not load badge /usr/share/hypnotix/pictures/badges/uk.png
Could not load badge /usr/share/hypnotix/pictures/badges/ireland.png
Could not load badge /usr/share/hypnotix/pictures/badges/malta.png
Could not load badge /usr/share/hypnotix/pictures/badges/netherlands.png
Could not load badge /usr/share/hypnotix/pictures/badges/belgium.png
Could not load badge /usr/share/hypnotix/pictures/badges/luxembourg.png
Could not load badge /usr/share/hypnotix/pictures/badges/denmark.png
Could not load badge /usr/share/hypnotix/pictures/badges/sweden.png
Could not load badge /usr/share/hypnotix/pictures/badges/norway.png
Could not load badge /usr/share/hypnotix/pictures/badges/iceland.png
Could not load badge /usr/share/hypnotix/pictures/badges/finland.png
Could not load badge /usr/share/hypnotix/pictures/badges/latvia.png
Could not load badge /usr/share/hypnotix/pictures/badges/estonia.png
Could not load badge /usr/share/hypnotix/pictures/badges/lithuania.png
Could not load badge /usr/share/hypnotix/pictures/badges/ukraine.png
Could not load badge /usr/share/hypnotix/pictures/badges/georgia.png
Could not load badge /usr/share/hypnotix/pictures/badges/bulgaria.png
Could not load badge /usr/share/hypnotix/pictures/badges/poland.png
Could not load badge /usr/share/hypnotix/pictures/badges/hungary.png
Could not load badge /usr/share/hypnotix/pictures/badges/czech.png
Could not load badge /usr/share/hypnotix/pictures/badges/slovakia.png
Could not load badge /usr/share/hypnotix/pictures/badges/slovenia.png
Could not load badge /usr/share/hypnotix/pictures/badges/romania.png
Could not load badge /usr/share/hypnotix/pictures/badges/turkey.png
Could not load badge /usr/share/hypnotix/pictures/badges/iran.png
Could not load badge /usr/share/hypnotix/pictures/badges/afghanistan.png
Could not load badge /usr/share/hypnotix/pictures/badges/pakistan.png
Could not load badge /usr/share/hypnotix/pictures/badges/israel.png
Could not load badge /usr/share/hypnotix/pictures/badges/greece.png
Could not load badge /usr/share/hypnotix/pictures/badges/albania.png
Could not load badge /usr/share/hypnotix/pictures/badges/algeria.png
Could not load badge /usr/share/hypnotix/pictures/badges/france.png
Could not load badge /usr/share/hypnotix/pictures/badges/france.png
Could not load badge /usr/share/hypnotix/pictures/badges/spain.png
Could not load badge /usr/share/hypnotix/pictures/badges/spain.png
Could not load badge /usr/share/hypnotix/pictures/badges/portugal.png
Could not load badge /usr/share/hypnotix/pictures/badges/italy.png
Could not load badge /usr/share/hypnotix/pictures/badges/music.png
Could not load badge /usr/share/hypnotix/pictures/badges/germany.png
Could not load badge /usr/share/hypnotix/pictures/badges/spain.png
Could not load badge /usr/share/hypnotix/pictures/badges/usa.png
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 293, in on_category_button_clicked
    self.show_channels(group.channels)
  File "/usr/lib/hypnotix/hypnotix.py", line 323, in show_channels
    surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, self.window.get_scale_factor())
TypeError: Couldn't find foreign struct converter for 'cairo.Surface'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
Loading providers...
Free-IPTV: Downloading playlist...
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
Free-IPTV: Checking playlist...
Free-IPTV: Loading channels...
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

**Comment by Axel-Erfurt** [comment]
How did you installed hypnotix?

Does the folder /usr/share/hypnotix/pictures/badges/ exists?

try in Terminal

``` shell
ls /usr/share/hypnotix/pictures/badges/
```

**Comment by joaopa00** [comment]
I use the deb package available in this site. Here is the result of the command you requested
ls /usr/share/hypnotix/pictures/badges/
afghanistan.png  bostwana.png   denmark.png    honduras.png   japan.png          mexico.png       panama.png       singapore.png     turkey.png
albania.png      brazil.png     ecuador.png    hongkong.png   kenya.png          morocco.png      paraguay.png     slovakia.png      uganda.png
algeria.png      bulgaria.png   egypt.png      hungary.png    korea.png          movies.png       peru.png         slovenia.png      uk.png
andora.png       cameroon.png   esperanto.png  iceland.png    koweit.png         mozambique.png   philippines.png  south-africa.png  ukraine.png
angola.png       canada.png     estonia.png    india.png      laos.png           music.png        poland.png       spain.png         uruguay.png
argentina.png    chile.png      ethiopia.png   indonesia.png  latvia.png         namibia.png      portugal.png     sweden.png        usa.png
armenia.png      china.png      europe.png     irak.png       lebanon.png        nepal.png        romania.png      switzerland.png   uzbekistan.png
australia.png    colombia.png   finland.png    iran.png       liechtenstein.png  netherlands.png  russia.png       syria.png         venezuela.png
austria.png      costarica.png  france.png     ireland.png    lithuania.png      newzealand.png   rw.png           taiwan.png        vietnam.png
bahrain.png      croatia.png    georgia.png    israel.png     luxembourg.png     nicaragua.png    saudi.png        tanzania.png      wales.png
bangladesh.png   cuba.png       germany.png    italy.png      lybia.png          nigeria.png      scotland.png     thailand.png      yemen.png
barbados.png     cyprus.png     ghana.png      ivory.png      malaysia.png       norway.png       senegal.png      togo.png          zambia.png
belgium.png      czech.png      greece.png     jamaica.png    malta.png          pakistan.png     serbia.png       tunisia.png       zimbabwe.png

**Comment by Axel-Erfurt** [comment]
try 

```sudo apt install python3-gi-cairo```

**Comment by joaopa00** [comment]
Thanks. It did the trick. Now everything is fine. Maybe you could add this dependence in the deb package?

**Comment by kosmonavvt** [comment]
> Maybe you could add this dependence in the deb package?

It's already in dependencies
https://github.com/linuxmint/hypnotix/blob/master/debian/control#L19

**Comment by kosmonavvt** [comment]
> I use the deb package available in this site.

Maybe you installed outdated version?
Here's latest: http://packages.linuxmint.com/pool/main/h/hypnotix/hypnotix_2.0_all.deb

**Comment by Axel-Erfurt** [comment]
If someone comes to the hypnotix start page here and calls up "Releases", they automatically end up with version 1.1

**Comment by kosmonavvt** [comment]
That's question for @clefebvre - why 1.1 is marked as latest in [Releases](https://github.com/linuxmint/hypnotix/releases) - and - why newer versions does not have .deb packages uploaded
