### ISSUE TITLE
Channels no longer loading on Xstream provider

### ISSUE THREAD

**Issue by Danzig67** [linuxmint/hypnotix#247]
Was working fine but after a few days without loading the program, my Xstream provider no longer shows any channels. When run from terminal I get the following:

```
XTREAM "[Provider name]" Loading Channels

Loaded 65 Live Groups in 0.000 seconds

Loaded 3051 Live Streams in 0.000 seconds

Loaded 18 VOD Groups in 0.000 seconds

Loaded 6749 VOD Streams in 0.000 seconds

'NoneType' object is not subscriptable

Traceback (most recent call last):
  
File "/usr/lib/hypnotix/hypnotix.py", line 1323, in reload
    self.x.load_iptv()
 
 File "/usr/lib/hypnotix/xtream.py", line 583, in load_iptv
    if stream_channel['name'][0].isascii():

TypeError: 'NoneType' object is not subscriptable

Couldn't parse provider info:  [provider name]:::xtream:::[provider url]:::[my username]:::[my password]:::
```

Not sure what has gone wrong but the json files are still being generated correctly within .hypnotix/providers so I assume the account details are being correctly validated, it's just not loading the channel lists within the GUI.

**Comment by Danzig67** [comment]
Issue appears to have resolved itself by upgrading from v2.6 to latest version.
