### ISSUE TITLE
invalid literal for int() with base 10: when trying to add xstream provider

### ISSUE THREAD

**Issue by buconettin** [linuxmint/hypnotix#348]
Hi, I added my xstream provider with username and password.
It takes forever and nothing is happening.
I use arch linux and got hypnotix from AUR with yay. (v.4.6)
When I start hypnotix from terminal, it shows me how it shows me a series of successful Getting, Checking, Creating Channel list etc. And also shows the correct amount of Live Groups and VOD Streams etc. But then I get this error:

`invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 1599, in reload
    self.x.load_iptv()
  File "/usr/lib/hypnotix/xtream.py", line 636, in load_iptv
    the_group = next(
                ^^^^^
  File "/usr/lib/hypnotix/xtream.py", line 637, in <genexpr>
    (x for x in self.groups if x.group_id == int(stream_channel["category_id"])),
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
`

**Comment by buconettin** [comment]
I fixed it. Saw that its in python, so here is the fix:

line 629 should be:
`                                if stream_channel["category_id"] == "":
`

since it should compare with an empty string instead of 
``                                if stream_channel["category_id"] is None:`

**Comment by superolmo** [comment]
That's interesting, I see the problem, but I am wondering why I don't get the same error. What version of Python are you using?

**Comment by lakshminarayananb** [comment]
I'm facing the same error suddenly for xstream streams.
