### ISSUE TITLE
Doesn't start on Mint 19.3

### ISSUE THREAD

**Issue by hahlic** [linuxmint/hypnotix#45]
Doesn't start from menu. When started from terminal have some errors. Any help  :-)

`~$ Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 24, in <module>    import mpv
  File "/usr/lib/hypnotix/mpv.py", line 567, in <module>    _handle_func('mpv_render_context_create',               [MpvRenderCtxHandle, MpvHandle, POINTER(MpvRenderParam)],   c_int, ec_errcheck,     ctx=None)
  File "/usr/lib/hypnotix/mpv.py", line 478, in _handle_func    func = getattr(backend, name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libmpv.so.1: undefined symbol: mpv_render_context_create
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_hypnotix_hypnotix.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 24, in <module>    import mpv
  File "/usr/lib/hypnotix/mpv.py", line 567, in <module>    _handle_func('mpv_render_context_create',               [MpvRenderCtxHandle, MpvHandle, POINTER(MpvRenderParam)],   c_int, ec_errcheck,     ctx=None)
  File "/usr/lib/hypnotix/mpv.py", line 478, in _handle_func    func = getattr(backend, name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libmpv.so.1: undefined symbol: mpv_render_context_create
`

**Comment by dwvisser** [comment]
I am also on Linux Mint 19.3. I get a slightly different error on launch. I installed the v1.1 .deb, after first installing the imdbpy dependency by downloading a .deb from https://packages.ubuntu.com/focal/all/python3-imdbpy/download.

```bash
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
$ hypnotix 
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 24, in <module>
    import mpv
  File "/usr/lib/hypnotix/mpv.py", line 567, in <module>
    _handle_func('mpv_render_context_create',               [MpvRenderCtxHandle, MpvHandle, POINTER(MpvRenderParam)],   c_int, ec_errcheck,     ctx=None)
  File "/usr/lib/hypnotix/mpv.py", line 478, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libmpv.so.1: undefined symbol: mpv_render_context_create
```

**Comment by hahlic** [comment]
You can try python3-imdbpy from this place
http://lug.mtu.edu/ubuntu/pool/universe/i/imdbpy/python3-imdbpy_6.8-2_all.deb?
Maybe will help resolve your problem. That is advice from Clem, see by you self :-)
https://blog.linuxmint.com/?p=3983#comments
My problem is maybe related to my processor AMD Ryzen, who knows ???

**Comment by clefebvre** [comment]
What version of libmpv do you have?

**Comment by hahlic** [comment]
It say latest available version
libmvp1   0.27.2-1ubuntu1

**Comment by clefebvre** [comment]
Ok it looks like this would need an older version of python-mpv: https://github.com/jaseg/python-mpv/issues/116.

**Comment by clefebvre** [comment]
We could maybe ship with two versions of python-mpv, check the version of libmpv and depending on that load one or another...

**Comment by clefebvre** [comment]
I'm not keen on targeting older releases for development but we could do that as a one-time fix.

**Comment by ajoaespinola** [comment]
I did the workaround of installing an older version of python-mpv (v0.3.9, v0.3.10, v0.4.0, even the last one 0.5.2 just for the lols) but unfortunately didn't work. The same error appears.

```
ajoa@XXX:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
```

```
ajoa@ajoa-NV59:~$ apt list libmpv1 
Listing... Done
libmpv1/bionic,now 0.27.2-1ubuntu1 amd64 [installed]
```

```
ajoa@XXX:~$ pip3 list
...
python-mpv (0.3.10)
...
```

```
ajoa@XXX:~$ hypnotix 
ajoa@XXX:~$ Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 24, in <module>
    import mpv
  File "/usr/lib/hypnotix/mpv.py", line 567, in <module>
    _handle_func('mpv_render_context_create',               [MpvRenderCtxHandle, MpvHandle, POINTER(MpvRenderParam)],   c_int, ec_errcheck,     ctx=None)
  File "/usr/lib/hypnotix/mpv.py", line 478, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libmpv.so.1: undefined symbol: mpv_render_context_create
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_hypnotix_hypnotix.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 24, in <module>
    import mpv
  File "/usr/lib/hypnotix/mpv.py", line 567, in <module>
    _handle_func('mpv_render_context_create',               [MpvRenderCtxHandle, MpvHandle, POINTER(MpvRenderParam)],   c_int, ec_errcheck,     ctx=None)
  File "/usr/lib/hypnotix/mpv.py", line 478, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libmpv.so.1: undefined symbol: mpv_render_context_create


```
