### ISSUE TITLE
Unable to add Xtream playlist or remove the free playlist

### ISSUE THREAD

**Issue by jakesilly** [linuxmint/hypnotix#48]
If I open hypnotix from the menu, I have no idea what is going on. I just see that nothing happens when I click on all the necessary buttons. When opened from the console however, I do see some logging:

Trying to remove the free playlist:
~$ Loading providers...
Free-IPTV: Getting playlist...
Free-IPTV: Checking playlist...
Free-IPTV: Loading channels...
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 774, in on_delete_button_clicked
    self.navigate_to("delete_page", name=provider.name)
TypeError: wrapper() got an unexpected keyword argument 'name'
Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 774, in on_delete_button_clicked
    self.navigate_to("delete_page", name=provider.name)
TypeError: wrapper() got an unexpected keyword argument 'name'

Trying to add my own Xtream playlist:
~$ Loading providers...
Free-IPTV: Downloading playlist...
Free-IPTV: Checking playlist...
Free-IPTV: Loading channels...
Shenzen: Downloading playlist...
Shenzen: Checking playlist...
Loading providers...
Free-IPTV: Downloading playlist...
Free-IPTV: Checking playlist...
Free-IPTV: Loading channels...
Shenzen: Downloading playlist...
Shenzen: Checking playlist...

There is however no Shenzen playlist to select after I added it. The only one remains the free list.
I'm running it on Ubuntu 20.04, updated today, downloaded the .deb from github and installed it with apt.

I have multiple paid Xtream subscriptions, none of them work on hypnotix but they do on IPTV Smarters on my Android TV box.

**Comment by ciorci** [comment]
same here.. archlinux kernel 5.9.10 gnome 3.38.2 hypnotix from aur

**Comment by LizziAS** [comment]
Build hypnotic-git

**Comment by ciorci** [comment]
thanks but i get the same result

**Comment by ciorci** [comment]
in ~/.hypnotix/providers every config file added for Xtream providers contain only "Access Denied."

**Comment by ciorci** [comment]
no problem when adding a m3u config file

**Comment by Axel-Erfurt** [comment]
look at [49#](https://github.com/linuxmint/hypnotix/issues/49#issuecomment-747552974) for edit and delete

**Comment by dlm21** [comment]
I have the same issue with not being able to add xtreme accounts. 
Looking at the content of the ~/.hypnotix/providers/$xtremeacctname shows what appears to be an HTML dump of a webpage.
If I convert the XC URL, user and pass into an m3u URL, it adds it just fine.

The version from the "About" menu option shows __DEB_VERSION__ , which might be an artifact of the Arch linux package I'm using, which says the version is 1.4-1. I installed hypnotix-git (1.4.r0.g01f9b87-1) as well and it behaves exactly the same.

**Comment by superolmo** [comment]
If any of you want to try, I have a pull request open with Xtream support #148
