### ISSUE TITLE
error running program on Mint 19.3

### ISSUE THREAD

**Issue by pakair** [linuxmint/hypnotix#92]
Mint MATE 19.3 (up-to-date), installed the deb file, installed libmpv1, libmpv-dev

user@T5600:~$ hypnotix
$ Traceback (most recent call last):
  File "/usr/lib/hypnotix/hypnotix.py", line 21, in <module>
    import mpv
  File "/usr/lib/hypnotix/mpv.py", line 567, in <module>
    _handle_func('mpv_render_context_create',               [MpvRenderCtxHandle, MpvHandle, POINTER(MpvRenderParam)],   c_int, ec_errcheck,     ctx=None)
  File "/usr/lib/hypnotix/mpv.py", line 478, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libmpv.so.1: undefined symbol: mpv_render_context_create

**Comment by pakair** [comment]
On Mint 20.1 there is libmpv.so.1.107.0 in /usr/lib/x86_64-linux-gnu/ but on Mint 19.3 there is libmpv.so.1.25.0 

Is there a way to bring in the newer library? thx

**Comment by ckorder** [comment]
Packaging the application as appimage should fix the issue and would make it distro universal usable. If that's intended I would love to see this.

**Comment by Guyverix** [comment]
@pakair At least you can manually get it in place by compiling MPV from here: https://github.com/mpv-player/mpv
I know it is a PITA, but on my Mint 19 it works, and you are not stuck waiting for a fix to be implemented.

**Comment by MGHPF** [comment]
Can somebody please provide a simple howto for unexperienced users and newbies to linux to fix the issue or provide a beginners-howto to work around the issue?

I am getting this error on my 32bit 19.3 Mint system and I don't know how to resolve it. I can't update to newer Mint to resolve:
[hypnotix_error_Mint19-3_32bit.txt](https://github.com/linuxmint/hypnotix/files/7919835/hypnotix_error_Mint19-3_32bit.txt)
